### ISSUE TITLE
Salary Predictor 

### ISSUE THREAD

**Issue by shreyasZ10** [avinashkranjan/Amazing-Python-Scripts#507] opened 2021-03-11 16:38 UTC
# Aim
I am a participant of GSSOC'21.
- What is the objective of the Script
- Objective of this project is to build a web-app such that given the skills of a person, in which sector he/she wish to work, what is the job location and which position he/she is applying for, This web-app can predict what could be his/her average annual salary

# Details

- What the features will your script have
- Random forest for preparing a model on data.
- Deploy using Flask framework.

**Comment by kaustubhgupta** [comment] 2021-03-12 17:05
Hi @shreyasZ10, I can assign this issue to you but we can only accept script/CLI/GUI (not web app) version of this. So can you do that?

**Comment by aliya-rahmani** [comment] 2021-03-13 04:33
@kaustubhgupta  Wanted to ask if we can work on some already assigned issues?

**Comment by kaustubhgupta** [comment] 2021-03-13 04:36
@aliya-rahmani actually no, until the user makes the PR, we can't assign other person. If the person fails to make the PR, then the issue is tagged as up-for-grab. Issues with this label are available for everyone.

**Comment by shreyasZ10** [comment] 2021-03-13 06:13
There is indeed a python script for all the operations involved. Also it has jupyter Notebook for data visualization and various data preprocessing. The only thing is, as it is a machine learning model it takes a lot of parameters as input basis on which it predicts salary of a person. Such an input is very difficult to obtain using a CLI/GUI so it is better to use a webapp for dynamic input from user.

**Comment by kaustubhgupta** [comment] 2021-03-13 06:23
@shreyasZ10 as you create a flask web app, take the inputs from the form and then pass it to the model, implement the same by taking inputs from the terminal. You can create several print statements for each parameter or use arg parser module to get them at one go

**Comment by shreyasZ10** [comment] 2021-03-13 06:50
I will try it as you said and then make a  pr of the same. Kindly assign me this issue.

**Closed** 2021-03-20 16:16 UTC
Labels: GSSOC21, Level2, assigned, enhancement
