### ISSUE TITLE
Script to auto fill Google Forms

### ISSUE THREAD

**Issue by avinashkranjan** [avinashkranjan/Amazing-Python-Scripts#82] opened 2020-10-05 17:30 UTC
# Aim

- Write a script to auto fill Google Forms.

# Details

- Create a dummy form for reference.
- Write a script to auto fill the forms reading from a CSV file for given data.
- Which Users can change as per their requirement.

**Comment by TheBlckCat** [comment] 2020-10-06 03:36
Hello! ✌️,
Maybe I can do this, although I'm not sure, but I will try.
Question: don't you have any problems if I use selenium?

**Comment by avinashkranjan** [comment] 2020-10-06 05:07
@TheBlckCat No, I don't have any problem...Sure Go ahead..

**Comment by TheBlckCat** [comment] 2020-10-07 02:02
Hi @avinashkranjan ✌️,
The code is almost done, but I have a few questions before I make the pull request.
* Does the csv file have to have data to fill the form once or can it have data to fill the form multiple times?
* Sorry, but I don't know what you mean by "Which users can change based on your requirements", can you tell me more?
* Should the program work for any form or just the example form?

That's all 😄 , thanks.

**Comment by avinashkranjan** [comment] 2020-10-07 05:48
@TheBlckCat Here goes answers to all your doubts.

- It should have data to fill forms multiple times cause if you want to fill the form once, you can directly hard code it in python script.

- You make a dummy google form and prepare a dummy csv file to fill the form, So, if someone wishes to use the script they can changes the link of google form and data of csv to fill the form.

- For now just that example form, rest same as second point.

**Comment by TheBlckCat** [comment] 2020-10-10 03:32
Hello! I have bad news :( , I can not do the program, it is very difficult for me. The script automatically fills in all the fields of the form with the data from the csv file, the problem is that I don't know how to make a generic program that can work with any form (which automatically detects the elements). Thanks for giving me the opportunity but I don't think I can do it.

**Comment by geekymeeky** [comment] 2020-10-11 11:28
I would like to work on this issue

**Comment by avinashkranjan** [comment] 2020-10-11 12:35
@geekymeeky Sure go ahead..

**Comment by avinashkranjan** [comment] 2020-11-10 17:59
Any Updates @geekymeeky

**Comment by saiharsha-22** [comment] 2021-01-03 06:15
@avinashkranjan I am a participant of SWOC 2021, I would like to work on this issue. Can you assign this is issue to me.

**Comment by avinashkranjan** [comment] 2021-01-03 06:50
Sure @saiharsha-22 Go ahead .. If you need any help you can always ask me or the mentors.. go ahead with scripting..Assigned to you..

**Comment by saiharsha-22** [comment] 2021-01-03 07:13
@avinashkranjan Thank you for assigning the issue. I will try my best to solve the issue

**Comment by saiharsha-22** [comment] 2021-01-06 08:46
@avinashkranjan  I have solved this issue, can you check the working video I have attached the video

https://user-images.githubusercontent.com/61947484/103747705-1029fb00-5029-11eb-8307-fcef2c8a3048.mp4

**Comment by saiharsha-22** [comment] 2021-01-06 10:20
@avinashkranjan I have created pull request #184. can you please check it once.

**Closed** 2021-01-08 06:16 UTC
Labels: SWoC 2021, assigned, enhancement, good first issue, hacktoberfest-2020, hard
